export const scoringRules = {
    goal: 5,
    assist: 3,
    cleanSheet: 5,
    photoOnBusStop: 4,
    late: -3,
    forgotJersey: -2,
    attendScrimmage: 2,
    firstAtField: 1,
    bestOutfit: 1,
    rugby: 1,
    card: -5,
    cursing: -4,
    noShow: -3,
    noSignUp: -2,
    nutmegged: -1,
    kitty: 5,
    scoreBike: 5,
    assistMaria: 3,
    scoreOutsideBox: 3,
    scoringHeader: 2,
    scoringVolley: 2,
    review: 4,
  };